### ISSUE TITLE
Merged years

### ISSUE THREAD

**Issue by dineiar** [kabrau/PyBibTextTools#2]
I found some wrong years on merged publications and just found the cause:

On `mergeEntry()`, you use the largest of the presented publication years. I think would be better to use the smaller one, as I've seen publications presented on .bibs as newer than they really are, but not older.

Let me know what you think about it.
If you agree with me, I'll submit a PR changing: `if (year2>yearOut)` to `if (year2<yearOut)`.

**Comment by kabrau** [comment]
agree, tks
